project:
  name: ${PROJECT_NAME}
  model_name: ${PROJECT_NAME}

training:
  entrypoint: app.train:train

validation:
  entrypoint: app.validate:validate

monitoring:
  workspace: ${PROJECT_NAME}
  project: ${PROJECT_NAME}
  entrypoint: app.monitor:check

registry:
  entrypoint: app.registry:register

deployment:
  namespace: default
  replicas: 1
  ecr_repository: ${PROJECT_NAME}
  entrypoint: app.deploy:deploy